### ISSUE TITLE
[NEW MODULE] Tadukoo Look & Feel

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooUtil#16]
**Describe the new module you're proposing**
A customizable look & feel that makes it easier to customize the style of the default Java components.

**Why should we add this new module?**
It will make it easier to customize the style of programs.

**Describe alternatives you've considered**
In Old Tadukoo Util, I was creating my own custom components in order to have them look the way I wanted them to. That process is needlessly more complicated as it avoids using the default Java components entirely (reinventing the wheel for those components). This approach would eliminate that need.

**Additional context**
This was technically already started and is partially present in Alpha v.0.1, but this Issue will be worded for the full project/process instead of just what needs done yet, in order to have it more properly documented here.

**Changes Needed**
The ultimate goal (at this point at least, future changes will involve more) is to replace the MetalLookAndFeel with a new TadukooLookAndFeel that allows for more customization through use of a theme, and customization on the level of individual components themselves too.

- [x] First of all, we need to create a LookAndFeel class extending MetalLookAndFeel and override the default and/or required methods (#20)
- [x] We need a Theme class (with a builder) to hold all the customizable items in, along with a ThemeFactory (to be able to easily create themes based off others - e.g. Metal, but with the customizable buttons (#21)

We will need to allow customizations for the following general items:
- [x] Paints (how to color pieces of the components, can be gradients, solid colors, textures, etc.) (#22)
- [x] Fonts (includes making it easier to choose a font you want to use from some standards) (#19)
- [x] Shapes (what shape components/pieces of them take) (#23)
- [x] Borders (#24)
- [x] Support using different component UI classes (e.g. use all the default Tadukoo ones, except we want the Metal Button UI) (just involves including Class<ButtonUI> etc. in Tadukoo Theme, which would be added on a per-component UI basis)
- [x] Support adding custom defaults to the defaults table (by category) (#25)

We will need to support those customizations in the components that Metal uses:
- [ ] ButtonUI
- [ ] CheckBoxUI
- [ ] ComboBoxUI
- [ ] DesktopIconUI
- [ ] FileChooserUI
- [ ] InternalFrameUI
- [ ] LabelUI
- [ ] PopupMenuSeparatorUI
- [ ] ProgressBarUI
- [ ] RadioButtonUI
- [ ] RootPaneUI
- [ ] ScrollBarUI
- [ ] ScrollPaneUI
- [ ] SeparatorUI
- [ ] SliderUI
- [ ] SplitPaneUI
- [ ] TabbedPaneUI
- [ ] TextFieldUI
- [ ] ToggleButtonUI
- [ ] ToolBarUI
- [ ] ToolTipUI
- [ ] TreeUI

**Comment by Tadukoo** [comment]
Note: Will be making sub-items for the above list, and more details will be given in them (this is an Epic after all)

**Comment by Tadukoo** [comment]
Tadukoo Look & Feel is now present in the Tadukoo View project, and this item has been moved there.
