### ISSUE TITLE
[FEATURE] MappedPojos

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooUtil#39]
**Describe the solution you'd like**
Add MappedPojo, OrderedMappedPojo, and a Table for MappedPojos

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
None

**Additional context**
Part of #4

**TODO List**
- [x] Create MappedPojo (interface)
- [x] Create AbstractMappedPojo (simple abstract implementation of MappedPojo)
- [x] Create OrderedMappedPojo (interface extending MappedPojo that controls key order)
- [x] Create AbstractOrderedMappedPojo (simple extension of AbstractMappedPojo that implements OrderedMappedPojo - but does not implement key order, leaving it to sub-classes)
- [x] Create Table (class that holds MappedPojos)
