### ISSUE TITLE
[FEATURE] Form Class

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooUtil#41]
**Describe the solution you'd like**
Add a Form class

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
None

**Additional context**
Part of #4

**TODO List**
- [x] Create Form (interface)
- [x] Create AbstractForm (class)
- [x] Relies on FormField (#40)
- [x] JUnit testing
