### ISSUE TITLE
[FEATURE] StringFormField

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooUtil#42]
**Describe the solution you'd like**
A FormField for Strings.

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
None

**Additional context**
Part of #4

**TODO List**
- [x] Include StringFieldType - can be normal (JTextField), title (a JLabel), or password (hiding what's typed using JPasswordField)
- [x] Editable - whether the user can edit the field or not
- [x] Columns - keep as -1 to default to string's size, can use to set field size
