### ISSUE TITLE
[FEATURE] TadukooTable

### ISSUE THREAD

**Issue by Tadukoo** [Tadukooverse/TadukooUtil#47]
**Describe the solution you'd like**
Create TadukooTable to make it easier to handle a JTable component with a Table (MappedPojo related Table - #39)

**Is your feature request related to a problem? Please describe.**
No

**Describe alternatives you've considered**
None

**Additional context**
Part of #4

**TODO List**
- [x] Method to create from Table
- [x] Method to update Table's pojos
- [x] Methods to make it simple to add rows
